/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as VipRouteImport } from './routes/vip'
import { Route as MxRouteImport } from './routes/mx'
import { Route as ChatPrivadoMxRouteImport } from './routes/chat-privado-mx'
import { Route as ChatPrivadoRouteImport } from './routes/chat-privado'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiChatLiveMxRouteImport } from './routes/api/chat-live-mx'
import { Route as ApiChatLiveRouteImport } from './routes/api/chat-live'

const VipRoute = VipRouteImport.update({
  id: '/vip',
  path: '/vip',
  getParentRoute: () => rootRouteImport,
} as any)
const MxRoute = MxRouteImport.update({
  id: '/mx',
  path: '/mx',
  getParentRoute: () => rootRouteImport,
} as any)
const ChatPrivadoMxRoute = ChatPrivadoMxRouteImport.update({
  id: '/chat-privado-mx',
  path: '/chat-privado-mx',
  getParentRoute: () => rootRouteImport,
} as any)
const ChatPrivadoRoute = ChatPrivadoRouteImport.update({
  id: '/chat-privado',
  path: '/chat-privado',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiChatLiveMxRoute = ApiChatLiveMxRouteImport.update({
  id: '/api/chat-live-mx',
  path: '/api/chat-live-mx',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiChatLiveRoute = ApiChatLiveRouteImport.update({
  id: '/api/chat-live',
  path: '/api/chat-live',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/chat-privado': typeof ChatPrivadoRoute
  '/chat-privado-mx': typeof ChatPrivadoMxRoute
  '/mx': typeof MxRoute
  '/vip': typeof VipRoute
  '/api/chat-live': typeof ApiChatLiveRoute
  '/api/chat-live-mx': typeof ApiChatLiveMxRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/chat-privado': typeof ChatPrivadoRoute
  '/chat-privado-mx': typeof ChatPrivadoMxRoute
  '/mx': typeof MxRoute
  '/vip': typeof VipRoute
  '/api/chat-live': typeof ApiChatLiveRoute
  '/api/chat-live-mx': typeof ApiChatLiveMxRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/chat-privado': typeof ChatPrivadoRoute
  '/chat-privado-mx': typeof ChatPrivadoMxRoute
  '/mx': typeof MxRoute
  '/vip': typeof VipRoute
  '/api/chat-live': typeof ApiChatLiveRoute
  '/api/chat-live-mx': typeof ApiChatLiveMxRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/chat-privado'
    | '/chat-privado-mx'
    | '/mx'
    | '/vip'
    | '/api/chat-live'
    | '/api/chat-live-mx'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/chat-privado'
    | '/chat-privado-mx'
    | '/mx'
    | '/vip'
    | '/api/chat-live'
    | '/api/chat-live-mx'
  id:
    | '__root__'
    | '/'
    | '/chat-privado'
    | '/chat-privado-mx'
    | '/mx'
    | '/vip'
    | '/api/chat-live'
    | '/api/chat-live-mx'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ChatPrivadoRoute: typeof ChatPrivadoRoute
  ChatPrivadoMxRoute: typeof ChatPrivadoMxRoute
  MxRoute: typeof MxRoute
  VipRoute: typeof VipRoute
  ApiChatLiveRoute: typeof ApiChatLiveRoute
  ApiChatLiveMxRoute: typeof ApiChatLiveMxRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/vip': {
      id: '/vip'
      path: '/vip'
      fullPath: '/vip'
      preLoaderRoute: typeof VipRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mx': {
      id: '/mx'
      path: '/mx'
      fullPath: '/mx'
      preLoaderRoute: typeof MxRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chat-privado-mx': {
      id: '/chat-privado-mx'
      path: '/chat-privado-mx'
      fullPath: '/chat-privado-mx'
      preLoaderRoute: typeof ChatPrivadoMxRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chat-privado': {
      id: '/chat-privado'
      path: '/chat-privado'
      fullPath: '/chat-privado'
      preLoaderRoute: typeof ChatPrivadoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/chat-live-mx': {
      id: '/api/chat-live-mx'
      path: '/api/chat-live-mx'
      fullPath: '/api/chat-live-mx'
      preLoaderRoute: typeof ApiChatLiveMxRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/chat-live': {
      id: '/api/chat-live'
      path: '/api/chat-live'
      fullPath: '/api/chat-live'
      preLoaderRoute: typeof ApiChatLiveRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ChatPrivadoRoute: ChatPrivadoRoute,
  ChatPrivadoMxRoute: ChatPrivadoMxRoute,
  MxRoute: MxRoute,
  VipRoute: VipRoute,
  ApiChatLiveRoute: ApiChatLiveRoute,
  ApiChatLiveMxRoute: ApiChatLiveMxRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
